### ISSUE TITLE
Better error handling when Open Baltimore API calls fail

### ISSUE THREAD

**Issue by circleofconfusion** [circleofconfusion/baltimore-hows-my-driving#17]
Open Baltimore moved their dataset to another site and API, which silently broke the bot. Send me a DM or some other alert when this sort of failure happens.

**Comment by circleofconfusion** [comment]
2021-01-19T02:13:51.799Z	b481c367-fc45-4911-aa48-abd1a7578fee	ERROR	Uncaught Exception	{
    "errorType": "SyntaxError",
    "errorMessage": "Unexpected token F in JSON at position 0",
    "stack": [
        "SyntaxError: Unexpected token F in JSON at position 0",
        "    at JSON.parse (<anonymous>)",
        "    at IncomingMessage.response.on (/var/task/open-baltimore.js:32:24)",
        "    at IncomingMessage.emit (events.js:203:15)",
        "    at endReadableNT (_stream_readable.js:1145:12)",
        "    at process._tickCallback (internal/process/next_tick.js:63:19)"
    ]
}
